/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techquizapp.gui;

import java.awt.Color;
import java.sql.SQLException;
import java.util.HashMap;

import javax.swing.JOptionPane;
import techquizapp.dao.ExamDAO;
import techquizapp.dao.QuestionDAO;
import techquizapp.pojo.Exam;
import techquizapp.pojo.Question;
import techquizapp.pojo.QuestionStore;
import techquizapp.pojo.UserProfile;

/**
 *
 * @author AYUSH
 */
public class SetQuestionFrame extends javax.swing.JFrame {

    /**
     * Creates new form SetQuestionPaperFrame
     */
    Color oldColor;
    int currQuestion=1;
     int questionRemain;
     Exam ex;
     QuestionStore questionList=new QuestionStore();
     
      String question;
        String correctOption;
        String opt1;
        String opt2;
        String opt3;
        String opt4;
    public SetQuestionFrame() {
       
    }
    public SetQuestionFrame(Exam exam){
         initComponents();
         ex=exam;
        setLocationRelativeTo(null);
        
        lbUserName.setText("Hello "+UserProfile.getUserName().toUpperCase());
    questionRemain =ex.getTotalQuestion();
      lbQuestionRemaining.setText(questionRemain+" Questions Remaning");
     
      lbQuestionNo.setText("Question No:"+currQuestion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbUserName = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbOption3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbOption1 = new javax.swing.JLabel();
        lbOption4 = new javax.swing.JLabel();
        lbQuestionNo = new javax.swing.JLabel();
        lbOption2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        txtOption1 = new javax.swing.JTextField();
        txtOption2 = new javax.swing.JTextField();
        txtOption3 = new javax.swing.JTextField();
        txtOption4 = new javax.swing.JTextField();
        jcbCorrectAnswer = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        lbQuestionRemaining = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbUserName.setBackground(new java.awt.Color(0, 0, 0));
        lbUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 102, 0));

        lbLogout.setBackground(new java.awt.Color(0, 0, 0));
        lbLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbLogout.setForeground(new java.awt.Color(255, 102, 0));
        lbLogout.setText("Logout");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbLogoutMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Java NetBeans\\TechQuizApp\\src\\Images\\questionpaper4.jpg")); // NOI18N

        lbOption3.setBackground(new java.awt.Color(0, 0, 0));
        lbOption3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbOption3.setForeground(new java.awt.Color(255, 102, 0));
        lbOption3.setText("Option 3");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Correct Answer:");

        lbOption1.setBackground(new java.awt.Color(0, 0, 0));
        lbOption1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbOption1.setForeground(new java.awt.Color(255, 102, 0));
        lbOption1.setText("Option 1");

        lbOption4.setBackground(new java.awt.Color(0, 0, 0));
        lbOption4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbOption4.setForeground(new java.awt.Color(255, 102, 0));
        lbOption4.setText("Option 4");

        lbQuestionNo.setBackground(new java.awt.Color(0, 0, 0));
        lbQuestionNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbQuestionNo.setForeground(new java.awt.Color(255, 102, 0));

        lbOption2.setBackground(new java.awt.Color(0, 0, 0));
        lbOption2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbOption2.setForeground(new java.awt.Color(255, 102, 0));
        lbOption2.setText("Option 2");

        txtQuestion.setColumns(20);
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        txtOption4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOption4ActionPerformed(evt);
            }
        });

        jcbCorrectAnswer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbCorrectAnswer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Option1", "Option2", "Option3", "Option4" }));

        btnNext.setBackground(new java.awt.Color(0, 0, 0));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 102, 0));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnDone.setBackground(new java.awt.Color(0, 0, 0));
        btnDone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDone.setForeground(new java.awt.Color(255, 102, 0));
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        lbQuestionRemaining.setBackground(new java.awt.Color(0, 0, 0));
        lbQuestionRemaining.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbQuestionRemaining.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbQuestionRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(lbLogout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbOption3)
                            .addComponent(txtOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOption1))
                        .addGap(179, 179, 179)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOption4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOption4)
                            .addComponent(txtOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOption2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(lbQuestionNo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnNext)
                        .addGap(71, 71, 71)
                        .addComponent(jButton2)
                        .addGap(67, 67, 67)
                        .addComponent(btnDone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbUserName)
                        .addComponent(lbLogout))
                    .addComponent(lbQuestionRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOption1)
                            .addComponent(lbOption2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOption3)
                            .addComponent(lbOption4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOption4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNext)
                            .addComponent(jButton2)
                            .addComponent(btnDone))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbQuestionNo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOption4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOption4ActionPerformed
       
    }//GEN-LAST:event_txtOption4ActionPerformed

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        LoginFrame login=new LoginFrame();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void lbLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseEntered
         oldColor=lbLogout.getForeground();
       lbLogout.setForeground(Color.white);
    }//GEN-LAST:event_lbLogoutMouseEntered

    private void lbLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseExited
         lbLogout.setForeground(oldColor);
    }//GEN-LAST:event_lbLogoutMouseExited

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(validateInput()==false){
             JOptionPane.showMessageDialog(null, "Please fill all the fields","Error",JOptionPane.ERROR_MESSAGE);
           return;
        }
       
        
         HashMap<String,String> ansMap=new HashMap();
       ansMap.put("Option1","Answer1");
       ansMap.put("Option2","Answer2");
       ansMap.put("Option3","Answer3");
       ansMap.put("Option4","Answer4");
        
       String correctAns=ansMap.get(correctOption);
        
        Question que=new Question(ex.getExamId(),currQuestion,question,correctAns,ex.getLanguage(),opt1,opt2,opt3,opt4);
       questionList.addQuestion(que);
       JOptionPane.showMessageDialog(null, "Question added","Done",JOptionPane.INFORMATION_MESSAGE);
      
       txtQuestion.setText("");
       txtOption1.setText("");
       txtOption2.setText("");
       txtOption3.setText("");
       txtOption4.setText("");
       
       
        if(questionRemain>0){
        lbQuestionRemaining.setText((--questionRemain)+" Questions Remaning");
        
        if(currQuestion<ex.getTotalQuestion()){
        currQuestion=currQuestion+1;
       lbQuestionNo.setText("Question No:"+(currQuestion));
        }
        
        }
        if(questionRemain==0){
            
        lbQuestionRemaining.setText(questionRemain+" Questions Remaning");
        btnNext.disable();
        txtQuestion.disable();
         txtOption1.disable();
       txtOption2.disable();
       txtOption3.disable();
       txtOption4.disable();
       jcbCorrectAnswer.disable();
        JOptionPane.showMessageDialog(null, "All questions has been completed click Done to insert into Database", "All Question Completed", JOptionPane.INFORMATION_MESSAGE);
        }
     
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        
        if((currQuestion)==ex.getTotalQuestion()){
           JOptionPane.showMessageDialog(null, "All Questions has been do you want to save?","Want to save in DB",JOptionPane.QUESTION_MESSAGE);
           try{
               boolean ans=ExamDAO.addExam(ex);
               if(ans){
               QuestionDAO.addQuestion(questionList);
               JOptionPane.showMessageDialog(null,"Question has been saved in DB successfully","Saved Successfully",JOptionPane.INFORMATION_MESSAGE);
                AdminOptionFrame adminFrame=new AdminOptionFrame();
                 adminFrame.setVisible(true);
                 this.dispose();
               }
               else{
                   JOptionPane.showMessageDialog(null, "Cannot save Questions in Db ","Error",JOptionPane.ERROR_MESSAGE);
                   return;
               }
               
           }
           catch(SQLException sqle)
           {
                JOptionPane.showMessageDialog(null, "Database Error Cannot Save questions in DB","DB Error",JOptionPane.ERROR_MESSAGE);
             sqle.printStackTrace();
           }}
       else
           JOptionPane.showMessageDialog(null, "Fill all question first","Question Remaning",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnDoneActionPerformed
 private boolean validateInput() {
          question=txtQuestion.getText().trim();
        correctOption=jcbCorrectAnswer.getSelectedItem().toString();
      opt1=txtOption1.getText().trim();
      opt2=txtOption2.getText().trim();
         opt3=txtOption3.getText().trim();
         opt4=txtOption4.getText().trim();
        if(question.isEmpty() || opt1.isEmpty() ||  opt2.isEmpty()||
                 opt3.isEmpty() || opt4.isEmpty() || correctOption.isEmpty())
             return false;
        else
            return true;
          }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SetPaperFrame paperFrame=new SetPaperFrame();
        paperFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetQuestionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jcbCorrectAnswer;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbOption1;
    private javax.swing.JLabel lbOption2;
    private javax.swing.JLabel lbOption3;
    private javax.swing.JLabel lbOption4;
    private javax.swing.JLabel lbQuestionNo;
    private javax.swing.JLabel lbQuestionRemaining;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JTextField txtOption1;
    private javax.swing.JTextField txtOption2;
    private javax.swing.JTextField txtOption3;
    private javax.swing.JTextField txtOption4;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables

   
}
